version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: zadaniya
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  task:
    build:
      context: .
      dockerfile: /task-creation-service/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - postgres


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: mikhi@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  postgres_data:
